import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from './Components/Navbar'
import Background from './Components/Background'




const sora = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
 
  return (
    <html lang="en">

       
      <body>
        <Background/>
        {children }
        
        </body>
      
      
    </html>
  )
}
